apiVersion: v1
kind: Secret
metadata:
  name: cluster-dagobah
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: cluster
    site: dagobah
    cluster.open-cluster-management.io/clusterset: grid
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  name: dagobah
  server: https://kubernetes.default.svc
  config: '{"tlsClientConfig":{"insecure":false}}'
