apiVersion: v1
kind: Secret
metadata:
  name: repo-quay-sbatsche
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
stringData:
  type: helm
  name: quay-sbatsche
  url: quay.io/sbatsche
  enableOCI: "true"
