apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grid-enrollment
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: quay.io/sbatsche
    chart: rhai-on-openshift-chart
    targetRevision: 3.6.0-aigrid.dev-3ce1f498
    helm:
      valuesObject:
        operator:
          enabled: false
        grid-enrollment:
          enabled: true
          host: enroll.apps.dagobah.hexfusion.local
          image:
            repository: quay.io/sbatsche/grid-enrollment
            digest: "sha256:691ca1ce8c0abae4474fbe9b10ced57232a00260488fa4641e88fe32d7b635b5"
          invites:
            dagobah:
              network: grid
            site-d:
              network: grid
  destination:
    server: https://kubernetes.default.svc
    namespace: grid-enrollment
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true, ServerSideApply=true]
