apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - limitador.yaml
  - mock-backends.yaml
  - deploy-gateway.yaml
  - svc-gateway.yaml
configMapGenerator:
  - name: praxis-gateway-v3-config
    files:
      - config/praxis.yaml
      - config/policy.yaml
generatorOptions:
  disableNameSuffixHash: true

images:
  - name: praxis-ai-gateway
    newName: quay.io/sbatsche/praxis-ai-gateway
    newTag: 0.6.0-geo-v3
