apiVersion: limitador.kuadrant.io/v1alpha1
kind: Limitador
metadata:
  name: quota
  namespace: ai-grid-v3
spec:
  limits:
    - namespace: grid-tokens
      name: per-subject-token-budget
      max_value: 2000
      seconds: 3600
      variables: ['descriptors[0]["sub"]']
      conditions: []
