---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/clusterrole-resources.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grid-operator-resources
  labels:
    helm.sh/chart: grid-operator-0.1.4
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-dagobah
    app.kubernetes.io/version: "v0.1.4"
    app.kubernetes.io/managed-by: Helm
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "patch"]
  - apiGroups: [""]
    resources: ["services"]
    resourceNames:
      - "grid-gateway"
      - "grid-operator-swim"
    verbs: ["get"]
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "create", "patch", "update"]
