---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/inferenceprovider.yaml
apiVersion: grid.praxis.fast/v1alpha1
kind: InferenceProvider
metadata:
  name: qwen3-site-a
  labels:
    helm.sh/chart: grid-operator-0.1.4
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-dagobah
    app.kubernetes.io/version: "v0.1.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gridNetworkRef: grid
  providerKind: vllm
  backendKind: local_model
  endpoint: "http://qwen3-kserve-workload-svc.ai-tenant-site-a.svc.cluster.local:8000"
  routingClusterRef: "site-a"
  models:
    - capabilities:
      - text_generation
      name: Qwen3-Coder-30B-A3B
---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/inferenceprovider.yaml
apiVersion: grid.praxis.fast/v1alpha1
kind: InferenceProvider
metadata:
  name: qwen3-site-b
  labels:
    helm.sh/chart: grid-operator-0.1.4
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-dagobah
    app.kubernetes.io/version: "v0.1.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gridNetworkRef: grid
  providerKind: vllm
  backendKind: local_model
  endpoint: "http://qwen3-kserve-workload-svc.ai-tenant-site-b.svc.cluster.local:8000"
  routingClusterRef: "site-b"
  models:
    - capabilities:
      - text_generation
      name: Qwen3-Coder-30B-A3B
