---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/rolebindings-resources.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grid-operator-resources
  namespace: grid
  labels:
    helm.sh/chart: grid-operator-0.1.4
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-dagobah
    app.kubernetes.io/version: "v0.1.4"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: grid-operator
    namespace: grid
roleRef:
  kind: ClusterRole
  name: grid-operator-resources
  apiGroup: rbac.authorization.k8s.io
