---
# Source: rhai-on-openshift-chart/charts/praxis-gateway/templates/service-metrics.yaml
apiVersion: v1
kind: Service
metadata:
  name: grid-gateway-metrics
  labels:
    helm.sh/chart: praxis-gateway-0.1.4
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-dagobah
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway-metrics
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: grid-gateway-metrics-tls
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9443
      targetPort: metrics
      protocol: TCP
  selector:
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-dagobah
