---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/clusterrolebinding-crd.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grid-operator-crd
  labels:
    helm.sh/chart: grid-operator-0.2.0
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-retail
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm
subjects:
  - kind: ServiceAccount
    name: grid-operator
    namespace: grid
roleRef:
  kind: ClusterRole
  name: grid-operator-crd
  apiGroup: rbac.authorization.k8s.io
