---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/gridnetwork.yaml
apiVersion: grid.praxis.fast/v1alpha1
kind: GridNetwork
metadata:
  name: "grid"
  labels:
    helm.sh/chart: grid-operator-0.1.5
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-retail
    app.kubernetes.io/version: "v0.1.5"
    app.kubernetes.io/managed-by: Helm
    grid.praxis.fast/auto-discover-sites: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gridId: "lab"
  seeds:
    - swim.hq.acme.lab:7946
  signalTransport:
    mode: "poll"
  peerTrust:
    mode: "spiffe"
  gatewayRefs:
    - name: "grid-gateway"
      namespace: "grid"
      localSiteName: "retail"
  tls:
    siteSecretRef:
      name: "grid-site-identity"
      namespace: "grid"
    caSecretRef:
      name: "grid-ca"
      namespace: "grid"
    swimKeyRef:
      name: "grid-swim-key"
      namespace: "grid"
