---
# Source: rhai-on-openshift-chart/charts/praxis-gateway/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grid-gateway
  labels:
    helm.sh/chart: praxis-gateway-0.1.4
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-hq
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  host: "grid.acme.lab"
  to:
    kind: Service
    name: grid-gateway
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
