---
# Source: rhai-on-openshift-chart/charts/praxis-gateway/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: grid-gateway
  labels:
    helm.sh/chart: praxis-gateway-0.1.4
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-hq
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  host: "grid.acme.lab"
  to:
    kind: Service
    name: grid-gateway
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    destinationCACertificate: |
      -----BEGIN CERTIFICATE-----
      MIIDUTCCAjmgAwIBAgIIHQzSfUKDhK8wDQYJKoZIhvcNAQELBQAwNjE0MDIGA1UE
      Awwrb3BlbnNoaWZ0LXNlcnZpY2Utc2VydmluZy1zaWduZXJAMTc2MDE0NDkyODAe
      Fw0yNTEwMTEwMTA4NDdaFw0yNzEyMTAwMTA4NDhaMDYxNDAyBgNVBAMMK29wZW5z
      aGlmdC1zZXJ2aWNlLXNlcnZpbmctc2lnbmVyQDE3NjAxNDQ5MjgwggEiMA0GCSqG
      SIb3DQEBAQUAA4IBDwAwggEKAoIBAQCjFsSHyWewBkrLbLPimNDUoXF0j3gd0ryo
      CXTAJ4Wv3QpSWADhacICRNCcy0wRO8BgvpiqOG7zKGOB8OsaVWe1Qu7D/s20U5fN
      ItQ65aea8/45h3wgfwGTCZGk/Z/ngVa2Xoc5zrpEo6VStc6iq7svjvUd6jCN200w
      rOxr3tU1cCCnel4W+T9lTuXvzVipBeZHhSwi8/6YEFTrLAi4UiaLOlz+tcny/hmy
      gfoIqAsdyGxh6PVXRqm7FLaz6/AkqnwxeV+lQQd7IsMVhXmpe8v37n3M+XTZKV7g
      0u8vkcQrGlIu7gsNnwlE5Cv0b2E42ZcdRsrwWnPFbKgRMamMomHjAgMBAAGjYzBh
      MA4GA1UdDwEB/wQEAwICpDAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQcXTIw
      0s9d8fJDGa9HWcmHECVVcjAfBgNVHSMEGDAWgBQcXTIw0s9d8fJDGa9HWcmHECVV
      cjANBgkqhkiG9w0BAQsFAAOCAQEAEYKwTQaIAXlf/oD+22ViouPMVSaJwmbyPi2h
      UMaewBiqeRtatV4zvAthInPbCHpmgX+InzW1QoCfEwN7GPaJvk4FxwzDRCiiQf3o
      zuQZfDsl/08MimtZ8wvoCnKG6mQd6hv+VqwwGKh9uZ+85denTZF4LLt/ftnIrXml
      z1NJlMubCIBLU4vFAMG+pKkCEt6bDBalGEAbfFwDHrfUtgB0lIlfmuPkE0ee6XMr
      sJdAODmtFK3yua4Abbo7Oo4CoTq9QwmIl6D2nyKN2rFOoOGYr6NuQ4ZFiHBvYFTa
      WnAIEHRCST/YcvCW2luma1K9QtFhaV+R7ho9i8jEw4ZnxK/OfQ==
      -----END CERTIFICATE-----
      
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
