---
# Source: rhai-on-openshift-chart/charts/praxis-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: grid-gateway
  labels:
    helm.sh/chart: praxis-gateway-0.1.4
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-hq
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: grid-gateway-listener-tls
spec:
  type: "ClusterIP"
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: "TCP"
  selector:
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-hq
