---
# Source: rhai-on-openshift-chart/charts/praxis-gateway/templates/servicemonitor.yaml
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: grid-gateway-metrics
  labels:
    helm.sh/chart: praxis-gateway-0.1.4
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-hq
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: praxis-gateway
      app.kubernetes.io/instance: grid-hq
      app.kubernetes.io/component: gateway-metrics
  endpoints:
    - port: metrics
      scheme: https
      path: /metrics
      interval: 5s
      tlsConfig:
        serverName: grid-gateway-metrics.grid.svc
        ca:
          configMap:
            name: "openshift-service-ca.crt"
            key: "service-ca.crt"
      metricRelabelings:
        # Praxis names the upstream cluster "cluster", which ACM sets to the managed cluster.
        - sourceLabels: [cluster]
          regex: "(.+)"
          targetLabel: backend
        - action: labeldrop
          regex: cluster
