---
# Source: rhai-on-openshift-chart/charts/praxis-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grid-gateway
  labels:
    helm.sh/chart: praxis-gateway-0.1.4
    app.kubernetes.io/name: praxis-gateway
    app.kubernetes.io/instance: grid-site-d
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: praxis-gateway
      app.kubernetes.io/instance: grid-site-d
  template:
    metadata:
      labels:
        app.kubernetes.io/component: gateway
        app.kubernetes.io/instance: grid-site-d
        app.kubernetes.io/name: praxis-gateway
      annotations:
        checksum/config: 5e5921f740e78531f975820336eb600c31397a6db1aa728363b844ff27aadd75
    spec:
      enableServiceLinks: false
      automountServiceAccountToken: false
      terminationGracePeriodSeconds: 35
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: praxis
          image: quay.io/sbatsche/grid-gateway@sha256:e9a013b5c5e5221d4380359d5759940ab83ace9e10170dc00e6f2dbae6ed4e57
          imagePullPolicy: "IfNotPresent"
          args:
            - --config
            - /etc/praxis/praxis.yaml
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          ports:
            - name: http
              containerPort: 8080
              protocol: "TCP"
          readinessProbe:
            initialDelaySeconds: 3
            periodSeconds: 5
            tcpSocket:
              port: http
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 10
            tcpSocket:
              port: http
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "5"]
          volumeMounts:
            - name: config
              mountPath: /etc/praxis
              readOnly: true
            - name: tls
              mountPath: "/etc/praxis/tls"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: grid-gateway-config
            items:
              - key: "praxis.yaml"
                path: "praxis.yaml"
        - name: tls
          projected:
            sources:
              - secret:
                  name: "grid-site-identity"
                  items: [{ key: tls.crt, path: tls.crt }, { key: tls.key, path: tls.key }]
              - secret:
                  name: "grid-ca"
                  items: [{ key: ca.crt, path: ca.crt }]
