apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - site-a/authpolicy.yaml
  - site-a/gateway.yaml
  - site-a/modelref.yaml
  - site-a/subscription.yaml
  - site-b/authpolicy.yaml
  - site-b/gateway.yaml
  - site-b/modelref.yaml
  - site-b/subscription.yaml
