---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/inferenceprovider.yaml
apiVersion: grid.praxis.fast/v1alpha1
kind: InferenceProvider
metadata:
  name: "qwen3"
  labels:
    helm.sh/chart: grid-operator-0.1.4
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-factory
    app.kubernetes.io/version: "v0.1.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gridNetworkRef: "grid"
  providerKind: "vllm"
  backendKind: "local_model"
  endpoint: "http://optimized-baseline-epp.llm-d.svc.cluster.local:80"
  routingClusterRef: "factory"
  siteSelector:
    matchLabels:
      app.kubernetes.io/instance: grid-factory
  models:
    - capabilities:
      - text_generation
      name: Qwen3-Coder-30B-A3B
  metricsConfig:
    metricsEndpoint: http://optimized-baseline-epp.llm-d.svc:9090
    path: /metrics
    poolName: optimized-baseline
    signalNames:
      kvCacheUtilization: llm_d_epp_average_kv_cache_utilization
      queueDepth: llm_d_epp_average_queue_size
