---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grid-operator
  labels:
    helm.sh/chart: grid-operator-0.2.0
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-factory
    app.kubernetes.io/version: "v0.2.0"
    app.kubernetes.io/managed-by: Helm
