apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: grid-operator
    grid.praxis-proxy.io/purpose: swim-seed
  name: grid-operator-swim
  namespace: grid-system
spec:
  ports:
  - name: swim-tcp
    port: 7946
    protocol: TCP
    targetPort: 7946
  - name: swim-udp
    port: 7946
    protocol: UDP
    targetPort: 7946
  selector:
    app.kubernetes.io/name: grid-operator
  type: ClusterIP

