---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/inferenceprovider.yaml
apiVersion: grid.praxis.fast/v1alpha1
kind: InferenceProvider
metadata:
  name: qwen3-hq-east
  labels:
    helm.sh/chart: grid-operator-0.1.4
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-hq
    app.kubernetes.io/version: "v0.1.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gridNetworkRef: grid
  providerKind: vllm
  backendKind: local_model
  endpoint: "http://qwen3-kserve-workload-svc.ai-tenant-site-a.svc.cluster.local:8000"
  routingClusterRef: "hq-east"
  models:
    - capabilities:
      - text_generation
      name: Qwen3-Coder-30B-A3B
  metricsConfig:
    auth:
      type: serviceAccountToken
    metricsEndpoint: https://qwen3-epp-service.ai-tenant-site-a.svc:9090
    path: /metrics
    poolName: qwen3-inference-pool
    signalNames:
      kvCacheUtilization: llm_d_epp_average_kv_cache_utilization
      queueDepth: llm_d_epp_average_queue_size
    tls:
      caConfigMapRef:
        key: service-ca.crt
        name: openshift-service-ca.crt
        namespace: grid
---
# Source: rhai-on-openshift-chart/charts/grid-operator/templates/inferenceprovider.yaml
apiVersion: grid.praxis.fast/v1alpha1
kind: InferenceProvider
metadata:
  name: qwen3-hq-west
  labels:
    helm.sh/chart: grid-operator-0.1.4
    app.kubernetes.io/name: grid-operator
    app.kubernetes.io/instance: grid-hq
    app.kubernetes.io/version: "v0.1.4"
    app.kubernetes.io/managed-by: Helm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gridNetworkRef: grid
  providerKind: vllm
  backendKind: local_model
  endpoint: "http://qwen3-kserve-workload-svc.ai-tenant-site-b.svc.cluster.local:8000"
  routingClusterRef: "hq-west"
  models:
    - capabilities:
      - text_generation
      name: Qwen3-Coder-30B-A3B
  metricsConfig:
    auth:
      type: serviceAccountToken
    metricsEndpoint: https://qwen3-epp-service.ai-tenant-site-b.svc:9090
    path: /metrics
    poolName: qwen3-inference-pool
    signalNames:
      kvCacheUtilization: llm_d_epp_average_kv_cache_utilization
      queueDepth: llm_d_epp_average_queue_size
    tls:
      caConfigMapRef:
        key: service-ca.crt
        name: openshift-service-ca.crt
        namespace: grid
