apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: limitador-data
  namespace: grid-system
  labels:
    app: limitador
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # storageClassName omitted -> cluster default (lvms-vg1)
