apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grid-gateway
  name: grid-gateway
  namespace: grid-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grid-gateway
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grid-gateway
    spec:
      enableServiceLinks: false
      containers:
        - name: envoy
          image: docker.io/envoyproxy/envoy:v1.31-latest
          args: ["-c", "/etc/envoy/envoy.yaml"]
          ports:
            - { containerPort: 8443, protocol: TCP }
          volumeMounts:
            - { mountPath: /etc/envoy, name: config }
            - { mountPath: /etc/grid/server, name: server-tls, readOnly: true }
      volumes:
        - name: config
          configMap: { name: grid-gateway-envoy-config, defaultMode: 420 }
        - name: server-tls
          secret: { secretName: grid-gateway-server-tls, defaultMode: 420 }
